//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JanaFandEntities : DbContext
    {
        public JanaFandEntities()
            : base("name=JanaFandEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Features> Features { get; set; }
        public virtual DbSet<Product_Features> Product_Features { get; set; }
        public virtual DbSet<Product_Galleries> Product_Galleries { get; set; }
        public virtual DbSet<Product_Groups> Product_Groups { get; set; }
        public virtual DbSet<Product_Selected_Groups> Product_Selected_Groups { get; set; }
        public virtual DbSet<Product_Tags> Product_Tags { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Product_Comments> Product_Comments { get; set; }
        public virtual DbSet<FactorDetails> FactorDetails { get; set; }
        public virtual DbSet<Factors> Factors { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<Slider_Galleries> Slider_Galleries { get; set; }
        public virtual DbSet<AboutUs> AboutUs { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<OurChoice> OurChoice { get; set; }
        public virtual DbSet<ContactUs> ContactUs { get; set; }
        public virtual DbSet<ContactCommant> ContactCommant { get; set; }
        public virtual DbSet<SocialNetwork> SocialNetwork { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
    }
}
