//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Comments
    {
        public int CommentID { get; set; }
        public int ProductID { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Name { get; set; }
        public Nullable<int> PersonID { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
