//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Selected_Groups
    {
        public int PG_ID { get; set; }
        public int ProductID { get; set; }
        public int GroupID { get; set; }
    
        public virtual Product_Groups Product_Groups { get; set; }
        public virtual Products Products { get; set; }
    }
}
