//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Slider()
        {
            this.Slider_Galleries = new HashSet<Slider_Galleries>();
        }
    
        public int SliderID { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string ImageName { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime SratrDate { get; set; }
        public bool IsActive { get; set; }
        public string ShortDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Slider_Galleries> Slider_Galleries { get; set; }
    }
}
