//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialNetwork
    {
        public int NetwordID { get; set; }
        public string Logo { get; set; }
        public string Url { get; set; }
        public string Title { get; set; }
    }
}
